# Generated by Django 2.2.2 on 2019-06-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='event',
            field=models.CharField(choices=[('education event', 'Education Event'), ('automobile event', 'Automobile Event'), ('electronic gadget event', 'Electronic Gadget Event'), ('health product event', 'Health Product Event'), ('beauty product event', 'Beauty Product Event')], default=None, max_length=100),
        ),
    ]
