# Generated by Django 2.2.2 on 2019-07-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190628_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_request',
            name='gmail',
            field=models.EmailField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='decoration',
            field=models.CharField(choices=[('balloon decoration', 'Balloon Decoration'), ('flower decoration', 'Flower Decoration'), ('mall decoration', 'Mall Decoration'), ('showroom decoration', 'Showroom Decoration'), ('festival theme decoration', 'Festival Theme Decoration'), ('stage decoration', 'Stage Decoration')], max_length=100),
        ),
    ]
