# Generated by Django 2.2.2 on 2019-07-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190701_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_request',
            name='mobile_number',
            field=models.BigIntegerField(),
        ),
    ]
