# Generated by Django 2.2.2 on 2019-07-07 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_user_request_seen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
