# Generated by Django 2.2.2 on 2019-07-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_delete_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='party_theme',
            field=models.CharField(choices=[('birthday party', 'Birthday Party'), ('cocktail party', 'Cocktail Party'), ('kitty party', 'Kitty Party'), ('pool party', 'Pool Party'), ('dj night', 'DJ Night'), ('bachlor party', 'Bachlor Party'), ('welcome & Farewell party', 'Welcome & Farewell Party'), ('fashion show', 'Fashion Show')], max_length=100),
        ),
    ]
