# Generated by Django 2.2.2 on 2019-07-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20190708_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='party_theme',
            field=models.CharField(choices=[('birthday party', 'Birthday Party'), ('cocktail party', 'Cocktail Party'), ('kitty party', 'Kitty Party'), ('pool party', 'Pool Party'), ('dj night', 'DJ Night'), ('bachlor party', 'Bachlor Party'), ('welcome and farewell party', 'Welcome and Farewell Party'), ('fashion show', 'Fashion Show')], max_length=100),
        ),
    ]
